/**
 * Os.h – AUTOSAR OS API Stub
 * AUTOSAR Release R22-11  |  AUTOSAR_SWS_OS
 *
 * Provides the OSEK/AUTOSAR OS API for the host-simulation build.
 * On a real target this header is generated by the OS configuration tool
 * and backed by the RTOS kernel.
 */

#ifndef OS_H
#define OS_H

#include "Std_Types.h"
#include "Compiler.h"

/* -------------------------------------------------------------------------
 * OS status codes  (OSEK OS §13.1)
 * ---------------------------------------------------------------------- */
typedef uint8 StatusType;

#define E_OS_ACCESS     ((StatusType)0x01u)
#define E_OS_CALLEVEL   ((StatusType)0x02u)
#define E_OS_ID         ((StatusType)0x03u)
#define E_OS_LIMIT      ((StatusType)0x04u)
#define E_OS_NOFUNC     ((StatusType)0x05u)
#define E_OS_RESOURCE   ((StatusType)0x06u)
#define E_OS_STATE      ((StatusType)0x07u)
#define E_OS_VALUE      ((StatusType)0x08u)

/* -------------------------------------------------------------------------
 * Application mode type
 * ---------------------------------------------------------------------- */
typedef uint8 AppModeType;

/* -------------------------------------------------------------------------
 * Task identifiers
 * ---------------------------------------------------------------------- */
typedef uint8 TaskType;
typedef TaskType * TaskRefType;

/* State values returned by GetTaskState */
typedef uint8 TaskStateType;
typedef TaskStateType * TaskStateRefType;

#define RUNNING     ((TaskStateType)0x00u)
#define WAITING     ((TaskStateType)0x01u)
#define READY       ((TaskStateType)0x02u)
#define SUSPENDED   ((TaskStateType)0x03u)

/* -------------------------------------------------------------------------
 * Alarm / Counter types
 * ---------------------------------------------------------------------- */
typedef uint32 TickType;
typedef TickType * TickRefType;

typedef uint8 AlarmType;

/* -------------------------------------------------------------------------
 * TASK macro – defines a task body
 * Usage: TASK(OsTask_10ms) { ... TerminateTask(); }
 * ---------------------------------------------------------------------- */
#define TASK(taskname)   void taskname##_taskbody(void)

/* -------------------------------------------------------------------------
 * DeclareTask – forward-declares the task body symbol (used in Os_Cfg.h)
 * ---------------------------------------------------------------------- */
#define DeclareTask(taskname)   extern void taskname##_taskbody(void)

/* -------------------------------------------------------------------------
 * OS service API
 * ---------------------------------------------------------------------- */
#ifdef __cplusplus
extern "C" {
#endif

/**
 * StartOS – initialises the OS and starts the configured application mode.
 * Does not return in a real RTOS; returns for host simulation.
 */
FUNC(void, OS_CODE) StartOS(AppModeType Mode);

/**
 * ShutdownOS – terminates the OS (calls ShutdownHook then halts).
 */
FUNC(void, OS_CODE) ShutdownOS(StatusType Error);

/**
 * TerminateTask – terminates the calling task.
 * Must be the last call in every basic task body.
 */
FUNC(StatusType, OS_CODE) TerminateTask(void);

/**
 * ActivateTask – activates a task by its identifier.
 */
FUNC(StatusType, OS_CODE) ActivateTask(TaskType TaskID);

/**
 * GetTaskID – returns the identifier of the currently running task.
 */
FUNC(StatusType, OS_CODE) GetTaskID(TaskRefType TaskID);

/**
 * GetTaskState – returns the current state of a task.
 */
FUNC(StatusType, OS_CODE) GetTaskState(TaskType TaskID, TaskStateRefType State);

/* -------------------------------------------------------------------------
 * OS hook callbacks – application must implement these
 * ---------------------------------------------------------------------- */

/**
 * StartupHook – called by the OS after initialisation, before task start.
 */
FUNC(void, OS_CODE) StartupHook(void);

/**
 * ShutdownHook – called by ShutdownOS before the OS halts.
 */
FUNC(void, OS_CODE) ShutdownHook(StatusType Error);

/**
 * ErrorHook – called whenever an OS service returns an error.
 */
FUNC(void, OS_CODE) ErrorHook(StatusType Error);

/**
 * PreTaskHook – called before the OS switches to a task.
 */
FUNC(void, OS_CODE) PreTaskHook(void);

/**
 * PostTaskHook – called after the OS leaves a task.
 */
FUNC(void, OS_CODE) PostTaskHook(void);

#ifdef __cplusplus
}
#endif

#endif /* OS_H */
