#pragma once

#include "ServiceRegistry.hpp"
#include <atomic>

namespace sdv::someip {

// Base class for client-side SOME/IP proxies generated by CommonAPI.
// Subclasses add typed method stubs and event subscriptions.
class ServiceProxy {
public:
    ServiceProxy(ServiceId serviceId, InstanceId instanceId,
                 ServiceRegistry& registry);
    virtual ~ServiceProxy();

    bool isAvailable() const;

    // Block until the service becomes available or timeout_ms elapses.
    bool waitAvailable(unsigned timeoutMs = 5000);

protected:
    ServiceId       serviceId_;
    InstanceId      instanceId_;
    ServiceRegistry& registry_;
    std::atomic<bool> available_{false};

    virtual void onAvailabilityChanged(bool available);
};

} // namespace sdv::someip
