/**
 * Det.h – AUTOSAR Default Error Tracer
 * AUTOSAR Release 22-11  |  AUTOSAR_SWS_DefaultErrorTracer
 *
 * Provides development-error and runtime-error reporting macros / stubs.
 * In a full AUTOSAR stack this module is configured and generated by the
 * AUTOSAR tool-chain.
 */

#ifndef DET_H
#define DET_H

#include "Std_Types.h"

/* ----- Module identification --------------------------------------------- */
#define DET_VENDOR_ID       0x0000u
#define DET_MODULE_ID       0x000Fu

/* ----- AUTOSAR version --------------------------------------------------- */
#define DET_AR_RELEASE_MAJOR_VERSION    22u
#define DET_AR_RELEASE_MINOR_VERSION    11u
#define DET_AR_RELEASE_PATCH_VERSION     0u

/* ----- Software version -------------------------------------------------- */
#define DET_SW_MAJOR_VERSION    1u
#define DET_SW_MINOR_VERSION    0u
#define DET_SW_PATCH_VERSION    0u

/**
 * Det_ReportError
 * Reports a Development Error to the DET module.
 *
 * @param ModuleId   Module identifier of the calling BSW module.
 * @param InstanceId Instance identifier of the calling module.
 * @param ApiId      Service ID (API function ID) of the calling function.
 * @param ErrorId    Error value (module-specific DET error code).
 * @return           Always E_OK (DET specification requirement).
 */
Std_ReturnType Det_ReportError(
    uint16 ModuleId,
    uint8  InstanceId,
    uint8  ApiId,
    uint8  ErrorId);

/**
 * Det_ReportRuntimeError
 * Reports a Runtime Error (non-development, recoverable).
 */
Std_ReturnType Det_ReportRuntimeError(
    uint16 ModuleId,
    uint8  InstanceId,
    uint8  ApiId,
    uint8  ErrorId);

/* ----- Test accessor functions (not part of AUTOSAR spec) ---------------- */
uint8  Det_GetLastErrorId(void);
uint8  Det_GetLastApiId(void);
uint16 Det_GetLastModuleId(void);
uint32 Det_GetErrorCount(void);
void   Det_Reset(void);

#endif /* DET_H */
