/**
 * SomeIp_Cfg.h – SOME/IP Pre-Compile Configuration
 * AUTOSAR Release 22-11
 * Reference: AUTOSAR_SWS_SOMEIPTransformer, AUTOSAR_SWS_ServiceDiscovery
 *
 * This header is normally generated by the AUTOSAR tool-chain from the
 * ARXML model.  Values here represent a sample standalone configuration.
 */

#ifndef SOMEIP_CFG_H
#define SOMEIP_CFG_H

#include "Std_Types.h"

/* ----- AUTOSAR version --------------------------------------------------- */
#define SOMEIP_CFG_AR_RELEASE_MAJOR_VERSION     22u
#define SOMEIP_CFG_AR_RELEASE_MINOR_VERSION     11u
#define SOMEIP_CFG_AR_RELEASE_PATCH_VERSION      0u

/* =========================================================================
 * Development-error detection (SWS requirement SOMEIP_00xxx)
 * STD_ON  → DET calls active  (used during development)
 * STD_OFF → DET calls removed (production build)
 * ========================================================================= */
#define SOMEIP_DEV_ERROR_DETECT         STD_ON

/* =========================================================================
 * Optional API switches
 * ========================================================================= */

/** Enable SomeIp_GetVersionInfo() and SomeIpSd_GetVersionInfo() */
#define SOMEIP_VERSION_INFO_API         STD_ON

/* =========================================================================
 * Buffer limits
 * ========================================================================= */

/** Maximum serialized frame size (bytes).  Must fit one Ethernet MTU. */
#define SOMEIP_MAX_FRAME_SIZE           1400u

/** Maximum SD payload size for one SD message */
#define SOMEIPSD_MAX_PAYLOAD_SIZE       512u

/** Maximum number of SD entries in one SD message */
#define SOMEIPSD_MAX_ENTRIES            16u

/* =========================================================================
 * SD timing defaults (all times in milliseconds)
 * ========================================================================= */
#define SOMEIPSD_INITIAL_DELAY_MIN_MS   0u
#define SOMEIPSD_INITIAL_DELAY_MAX_MS   500u
#define SOMEIPSD_CYCLIC_OFFER_DELAY_MS  1000u

/* =========================================================================
 * SomeIpSd_RxIndication PduId mapping
 * In a generated configuration these are assigned by PduR routing tables.
 * ========================================================================= */
#define SOMEIPSD_RX_PDU_ID              0x0000u

#endif /* SOMEIP_CFG_H */
