/**
 * Eth_17_GEthMac.c – Aurix TC34xx EQOS Ethernet MCAL Driver
 * AUTOSAR Release R22-11
 *
 * Two build modes are supported, selected by the pre-processor switch
 * ETH_17_GETH_MAC_HOST_SIM (defined in Eth_17_GEthMac_Cfg.h):
 *
 *  ┌──────────────────────────────────────────────────────────────────┐
 *  │  ETH_17_GETH_MAC_HOST_SIM defined (default)                      │
 *  │                                                                   │
 *  │  All Transmit calls → NodeTransport_SimTx() → UDP socket         │
 *  │  All Receive  calls → NodeTransport_SimRx() → RX callback        │
 *  │  All register accesses are no-ops (MCAL_REG32_* macros)          │
 *  │  Runs on Linux and Windows without any TC34xx hardware            │
 *  └──────────────────────────────────────────────────────────────────┘
 *
 *  ┌──────────────────────────────────────────────────────────────────┐
 *  │  ETH_17_GETH_MAC_HOST_SIM NOT defined                            │
 *  │                                                                   │
 *  │  Real EQOS MAC register access via MCAL_REG32_* macros           │
 *  │  DMA descriptor ring management (TX: 8 descs, RX: 8 descs)       │
 *  │  PHY management via MDIO (TJA1100 init sequence)                  │
 *  │  Requires TriCore toolchain (TASKING / GCC for TriCore)           │
 *  └──────────────────────────────────────────────────────────────────┘
 */

#include "Eth_17_GEthMac.h"
#include "Eth_17_GEthMac_Cfg.h"
#include "IfxEth_regdef.h"
#include "Mcal.h"
#include "EthIf.h"

#include <string.h>
#include <stdio.h>

#ifdef ETH_17_GETH_MAC_HOST_SIM
#  include "NodeTransport.h"
#  include "SomeIp.h"
#  include "SomeIp_SD.h"
#endif

/* =========================================================================
 * Module-static state
 * ====================================================================== */

/** Static configuration (populated by Eth_17_GEthMac_Init; used in HW path) */
static const Eth_17_GEthMac_ConfigType *Eth_Cfg = NULL;  /* PRQA S 1531 */

/** Current controller mode (read by GetControllerMode on both paths) */
static Eth_ModeType Eth_CtrlMode = ETH_MODE_DOWN;

#ifndef ETH_17_GETH_MAC_HOST_SIM
/** TX DMA descriptor ring (aligned to 32 bytes for EQOS hardware) */
static IfxEth_DmaDesc_t Eth_TxDescRing[ETH_17_GETH_MAC_TX_DESC_COUNT]
    MCAL_DSPR_DATA __attribute__((aligned(32)));

/** RX DMA descriptor ring */
static IfxEth_DmaDesc_t Eth_RxDescRing[ETH_17_GETH_MAC_RX_DESC_COUNT]
    MCAL_DSPR_DATA __attribute__((aligned(32)));

/** RX payload buffers (one per RX descriptor) */
static uint8 Eth_RxBuf[ETH_17_GETH_MAC_RX_DESC_COUNT][ETH_17_GETH_MAC_RX_BUF_LEN]
    MCAL_DSPR_DATA;

/** TX payload buffers (one per TX descriptor) */
static uint8 Eth_TxBuf[ETH_17_GETH_MAC_TX_DESC_COUNT][ETH_17_GETH_MAC_RX_BUF_LEN]
    MCAL_DSPR_DATA;

/** TX ring tail index (next descriptor to allocate) */
static uint8 Eth_TxTail = 0u;

/** TX ring head index (next descriptor to check for completion) */
static uint8 Eth_TxHead = 0u;
#endif  /* !HOST_SIM */

/* =========================================================================
 * Static configuration object
 * (Would normally be generated by the ARXML configuration tool)
 * ====================================================================== */

const Eth_17_GEthMac_ConfigType Eth_17_GEthMac_Config = {
    .CtrlIdx        = ETH_17_GETH_MAC_CTRL_IDX_0,
    .MacAddressHigh = ETH_17_GETH_MAC_ADDR_HIGH,
    .MacAddressLow  = ETH_17_GETH_MAC_ADDR_LOW,
    .PhyAddress     = ETH_17_GETH_MAC_PHY_ADDRESS,
    .MdioCrValue    = ETH_17_GETH_MAC_MDIO_CR_VALUE,
    .TxDescCount    = ETH_17_GETH_MAC_TX_DESC_COUNT,
    .RxDescCount    = ETH_17_GETH_MAC_RX_DESC_COUNT,
    .RxBufLenByte   = ETH_17_GETH_MAC_RX_BUF_LEN
};

/* =========================================================================
 * Eth_17_GEthMac_Init                                  [SWS_Eth_00027]
 * ====================================================================== */

FUNC(void, ETH_CODE)
Eth_17_GEthMac_Init(
    P2CONST(Eth_17_GEthMac_ConfigType, AUTOMATIC, ETH_APPL_CONST) CfgPtr)
{
    if (CfgPtr == NULL)
    {
        return;
    }
    Eth_Cfg      = CfgPtr;
    Eth_CtrlMode = ETH_MODE_DOWN;
    (void)Eth_Cfg;  /* suppress unused-variable in HOST_SIM mode */

#ifdef ETH_17_GETH_MAC_HOST_SIM
    printf("[Eth_MCAL] Init (host-sim): controller %u  MAC=%08lX:%08lX\n",
           (unsigned)CfgPtr->CtrlIdx,
           (unsigned long)CfgPtr->MacAddressHigh,
           (unsigned long)CfgPtr->MacAddressLow);
    printf("[Eth_MCAL] PHY addr=0x%02X  TX descs=%u  RX descs=%u\n",
           (unsigned)CfgPtr->PhyAddress,
           (unsigned)CfgPtr->TxDescCount,
           (unsigned)CfgPtr->RxDescCount);

#else
    /* --- Real TC34xx initialisation sequence ----------------------------- */

    /* 1. Enable ETH0 peripheral clock via CLC register */
    MCAL_REG32_CLRBITS(MCAL_TC34XX_ETH0_CLC, (uint32)0x00000001u);  /* DISR=0 */

    /* 2. Assert DMA software reset; poll until cleared */
    MCAL_REG32_SETBITS(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                    IFXETH_DMA_MODE_OFFSET),
                       IFXETH_DMA_MODE_SWR);
    /* (Production: add timeout loop on SWR bit) */

    /* 3. Configure AXI bus mode (burst lengths) */
    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_DMA_SYSBUS_MODE_OFFSET),
                     IFXETH_DMA_SBM_BLEN16 | IFXETH_DMA_SBM_BLEN8 |
                     IFXETH_DMA_SBM_BLEN4);

    /* 4. Program MAC address registers */
    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_ADDRESS0_HIGH_OFFSET),
                     CfgPtr->MacAddressHigh | (uint32)0x80000000u);  /* AE=1 */
    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_ADDRESS0_LOW_OFFSET),
                     CfgPtr->MacAddressLow);

    /* 5. Configure MAC for RMII 100 Mbps full-duplex */
    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_CONFIGURATION_OFFSET),
                     IFXETH_MAC_CFG_PS  |   /* MII/RMII port select   */
                     IFXETH_MAC_CFG_FES |   /* 100 Mbps               */
                     IFXETH_MAC_CFG_DM  |   /* Full duplex            */
                     IFXETH_MAC_CFG_ACS |   /* Auto pad/CRC strip     */
                     IFXETH_MAC_CFG_JD  |   /* Disable jabber         */
                     IFXETH_MAC_CFG_WD);    /* Disable watchdog       */

    /* 6. Configure MTL TX/RX queues and DMA descriptor rings */
    /* (Production: set up queue sizes, thresholds, descriptor list addresses) */

    /* 7. Initialise TJA1100 PHY via MDIO */
    (void)Eth_17_GEthMac_WriteMii(CfgPtr->CtrlIdx,
                                   CfgPtr->PhyAddress,
                                   IFXETH_TJA1100_BASIC_CTRL_REG,
                                   IFXETH_TJA1100_MASTER_MODE);
#endif
}

/* =========================================================================
 * Eth_17_GEthMac_SetControllerMode                     [SWS_Eth_00028]
 * ====================================================================== */

FUNC(Std_ReturnType, ETH_CODE)
Eth_17_GEthMac_SetControllerMode(
    VAR(uint8,        AUTOMATIC) CtrlIdx,
    VAR(Eth_ModeType, AUTOMATIC) CtrlMode)
{
    (void)CtrlIdx;

    if (CtrlMode == ETH_MODE_ACTIVE)
    {
#ifndef ETH_17_GETH_MAC_HOST_SIM
        MCAL_REG32_SETBITS(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                        IFXETH_MAC_CONFIGURATION_OFFSET),
                           IFXETH_MAC_CFG_TE | IFXETH_MAC_CFG_RE);
#else
        printf("[Eth_MCAL] Controller %u set to ACTIVE\n", (unsigned)CtrlIdx);
#endif
    }
    else
    {
#ifndef ETH_17_GETH_MAC_HOST_SIM
        MCAL_REG32_CLRBITS(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                        IFXETH_MAC_CONFIGURATION_OFFSET),
                           IFXETH_MAC_CFG_TE | IFXETH_MAC_CFG_RE);
#else
        printf("[Eth_MCAL] Controller %u set to DOWN\n", (unsigned)CtrlIdx);
#endif
    }

    Eth_CtrlMode = CtrlMode;
    return E_OK;
}

/* =========================================================================
 * Eth_17_GEthMac_GetControllerMode                     [SWS_Eth_00029]
 * ====================================================================== */

FUNC(Std_ReturnType, ETH_CODE)
Eth_17_GEthMac_GetControllerMode(
    VAR(uint8, AUTOMATIC)                           CtrlIdx,
    P2VAR(Eth_ModeType, AUTOMATIC, ETH_APPL_DATA)   CtrlModePtr)
{
    (void)CtrlIdx;
    if (CtrlModePtr == NULL) { return E_NOT_OK; }
    *CtrlModePtr = Eth_CtrlMode;
    return E_OK;
}

/* =========================================================================
 * Eth_17_GEthMac_ProvideTxBuffer                       [SWS_Eth_00087]
 * ====================================================================== */

FUNC(BufReq_ReturnType, ETH_CODE)
Eth_17_GEthMac_ProvideTxBuffer(
    VAR(uint8, AUTOMATIC)                              CtrlIdx,
    P2VAR(Eth_BufIdxType, AUTOMATIC, ETH_APPL_DATA)   BufIdxPtr,
    P2VAR(uint8 *, AUTOMATIC, ETH_APPL_DATA)           BufPtr,
    P2VAR(uint16, AUTOMATIC, ETH_APPL_DATA)            LenBytePtr)
{
    (void)CtrlIdx;

    if ((BufIdxPtr == NULL) || (BufPtr == NULL) || (LenBytePtr == NULL))
    {
        return BUFREQ_E_NOT_OK;
    }

#ifdef ETH_17_GETH_MAC_HOST_SIM
    /* In host-sim the NodeTransport handles its own buffer; we return a
     * module-static scratch buffer so upper BSW can format the frame. */
    static uint8 Eth_SimTxBuf[ETH_17_GETH_MAC_RX_BUF_LEN];
    *BufIdxPtr  = 0u;
    *BufPtr     = Eth_SimTxBuf;
    *LenBytePtr = ETH_17_GETH_MAC_RX_BUF_LEN;
#else
    uint8 nextTail = (uint8)((Eth_TxTail + 1u) %
                              (uint8)ETH_17_GETH_MAC_TX_DESC_COUNT);
    if (nextTail == Eth_TxHead)
    {
        return BUFREQ_E_BUSY;  /* TX ring full */
    }
    /* Check that the EQOS DMA no longer owns this descriptor */
    if ((Eth_TxDescRing[Eth_TxTail].Des3 & IFXETH_TX_DES3_OWN) != 0u)
    {
        return BUFREQ_E_BUSY;
    }
    *BufIdxPtr  = Eth_TxTail;
    *BufPtr     = Eth_TxBuf[Eth_TxTail];
    *LenBytePtr = ETH_17_GETH_MAC_RX_BUF_LEN;
#endif

    return BUFREQ_OK;
}

/* =========================================================================
 * Eth_17_GEthMac_Transmit                              [SWS_Eth_00088]
 * ====================================================================== */

FUNC(Std_ReturnType, ETH_CODE)
Eth_17_GEthMac_Transmit(
    VAR(uint8,          AUTOMATIC) CtrlIdx,
    VAR(Eth_BufIdxType, AUTOMATIC) BufIdx,
    VAR(Eth_FrameType,  AUTOMATIC) FrameType,
    VAR(boolean,        AUTOMATIC) TxConfirmation,
    VAR(uint16,         AUTOMATIC) LenByte,
    P2CONST(uint8, AUTOMATIC, ETH_APPL_DATA) PhysAddrPtr)
{
    (void)CtrlIdx;
    (void)FrameType;
    (void)TxConfirmation;
    (void)PhysAddrPtr;

#ifdef ETH_17_GETH_MAC_HOST_SIM
    /* In simulation, the "wire" is the NodeTransport UDP socket.
     * SomeIpSd_Transmit() is the integration point called by SomeIp_SD.c;
     * Eth_17_GEthMac_Transmit() is the lower path when upper BSW calls
     * EthIf_Transmit() directly (non-SD frames).
     * For the vehicle-network demo all traffic goes via SomeIpSd_Transmit(),
     * so this path is a stub for completeness. */
    static uint8 Eth_SimTxBuf[ETH_17_GETH_MAC_RX_BUF_LEN];
    (void)BufIdx;
    (void)memset(Eth_SimTxBuf, 0, sizeof(Eth_SimTxBuf));
    printf("[Eth_MCAL] Transmit: %u bytes (host-sim, non-SD frame)\n",
           (unsigned)LenByte);
#else
    /* Hand buffer to EQOS DMA */
    Eth_TxDescRing[BufIdx].Des0 = (uint32)(uintptr_t)Eth_TxBuf[BufIdx];
    Eth_TxDescRing[BufIdx].Des2 = (uint32)LenByte | (uint32)0x80000000u; /* BUF1V */
    Eth_TxDescRing[BufIdx].Des3 = IFXETH_TX_DES3_OWN |
                                   IFXETH_TX_DES3_FD  |
                                   IFXETH_TX_DES3_LD  |
                                   (uint32)LenByte;
    Eth_TxTail = (uint8)((BufIdx + 1u) % ETH_17_GETH_MAC_TX_DESC_COUNT);

    /* Ring doorbell: write tail pointer to DMA register */
    MCAL_REG32_WRITE(
        IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                    IFXETH_DMA_CH_BASE(0u) + IFXETH_DMA_CH_TX_DESC_LIST_ADDR_OFFSET),
        (uint32)(uintptr_t)&Eth_TxDescRing[Eth_TxTail]);
#endif

    return E_OK;
}

/* =========================================================================
 * Eth_17_GEthMac_Receive                               [SWS_Eth_00089]
 * ====================================================================== */

FUNC(void, ETH_CODE)
Eth_17_GEthMac_Receive(
    VAR(uint8, AUTOMATIC)                                         CtrlIdx,
    P2VAR(Eth_RxStatusType, AUTOMATIC, ETH_APPL_DATA)            RxStatusPtr)
{
    (void)CtrlIdx;

    if (RxStatusPtr == NULL) { return; }

#ifdef ETH_17_GETH_MAC_HOST_SIM
    /* In host-sim, NodeTransport's background receive thread delivers frames
     * directly via SomeIpSd_RxIndication().  The cyclic Receive poll is a
     * no-op because the transport layer is interrupt-driven (thread-based). */
    *RxStatusPtr = ETH_NOT_RECEIVED;

#else
    uint8 i;
    *RxStatusPtr = ETH_NOT_RECEIVED;

    for (i = 0u; i < ETH_17_GETH_MAC_RX_DESC_COUNT; i++)
    {
        if ((Eth_RxDescRing[i].Des3 & IFXETH_RX_DES3_OWN) == 0u)
        {
            /* Frame received – extract length and call upper layer */
            uint16 frameLen = (uint16)(Eth_RxDescRing[i].Des3 & IFXETH_RX_DES3_PL);
            EthIf_RxIndication(CtrlIdx,
                               ETHIF_ETHERTYPE_SOMEIP,
                               FALSE,
                               NULL,  /* physical address not parsed here */
                               Eth_RxBuf[i],
                               frameLen);
            /* Return descriptor to DMA */
            Eth_RxDescRing[i].Des3 = IFXETH_RX_DES3_OWN | IFXETH_RX_DES3_IOC;
            *RxStatusPtr = ETH_RECEIVED_MORE_DATA_AVAILABLE;
        }
    }
#endif
}

/* =========================================================================
 * Eth_17_GEthMac_TxConfirmation                        [SWS_Eth_00090]
 * ====================================================================== */

FUNC(void, ETH_CODE)
Eth_17_GEthMac_TxConfirmation(VAR(uint8, AUTOMATIC) CtrlIdx)
{
    (void)CtrlIdx;

#ifndef ETH_17_GETH_MAC_HOST_SIM
    while (Eth_TxHead != Eth_TxTail)
    {
        if ((Eth_TxDescRing[Eth_TxHead].Des3 & IFXETH_TX_DES3_OWN) != 0u)
        {
            break;  /* DMA still owns this descriptor */
        }
        EthIf_TxConfirmation(CtrlIdx, Eth_TxHead);
        Eth_TxHead = (uint8)((Eth_TxHead + 1u) % ETH_17_GETH_MAC_TX_DESC_COUNT);
    }
#endif
}

/* =========================================================================
 * Eth_17_GEthMac_GetVersionInfo                        [SWS_Eth_00091]
 * ====================================================================== */

FUNC(void, ETH_CODE)
Eth_17_GEthMac_GetVersionInfo(
    P2VAR(Std_VersionInfoType, AUTOMATIC, ETH_APPL_DATA) VersionInfoPtr)
{
    if (VersionInfoPtr == NULL) { return; }
    VersionInfoPtr->vendorID         = ETH_17_GETH_MAC_VENDOR_ID;
    VersionInfoPtr->moduleID         = ETH_17_GETH_MAC_MODULE_ID;
    VersionInfoPtr->sw_major_version = ETH_17_GETH_MAC_SW_MAJOR_VERSION;
    VersionInfoPtr->sw_minor_version = ETH_17_GETH_MAC_SW_MINOR_VERSION;
    VersionInfoPtr->sw_patch_version = ETH_17_GETH_MAC_SW_PATCH_VERSION;
}

/* =========================================================================
 * Eth_17_GEthMac_GetPhyLinkState (extended API)
 * ====================================================================== */

FUNC(boolean, ETH_CODE)
Eth_17_GEthMac_GetPhyLinkState(VAR(uint8, AUTOMATIC) CtrlIdx)
{
#ifdef ETH_17_GETH_MAC_HOST_SIM
    (void)CtrlIdx;
    return TRUE;  /* loopback is always "linked" */
#else
    uint16 basicStatus = 0u;
    if (Eth_Cfg == NULL) { return FALSE; }
    (void)Eth_17_GEthMac_ReadMii(CtrlIdx,
                                  Eth_Cfg->PhyAddress,
                                  IFXETH_TJA1100_BASIC_STATUS_REG,
                                  &basicStatus);
    return ((basicStatus & (uint16)0x0004u) != 0u) ? TRUE : FALSE;
#endif
}

/* =========================================================================
 * Eth_17_GEthMac_ReadMii / WriteMii  (MDIO access)
 * ====================================================================== */

FUNC(Std_ReturnType, ETH_CODE)
Eth_17_GEthMac_ReadMii(
    VAR(uint8, AUTOMATIC) CtrlIdx,
    VAR(uint8, AUTOMATIC) PhyAddr,
    VAR(uint8, AUTOMATIC) RegAddr,
    P2VAR(uint16, AUTOMATIC, ETH_APPL_DATA) RegDataPtr)
{
    (void)CtrlIdx;
    if (RegDataPtr == NULL) { return E_NOT_OK; }
#ifdef ETH_17_GETH_MAC_HOST_SIM
    *RegDataPtr = 0u;  /* PHY not present in simulation */
    (void)PhyAddr; (void)RegAddr;
#else
    uint32 mdioAddr = ((uint32)PhyAddr  << IFXETH_MDIO_PHYADDR_SHIFT) |
                      ((uint32)RegAddr  << IFXETH_MDIO_REGADDR_SHIFT)  |
                      ((uint32)Eth_17_GEthMac_Config.MdioCrValue << IFXETH_MDIO_CR_SHIFT) |
                      IFXETH_MDIO_READ | IFXETH_MDIO_GB;

    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_MDIO_ADDRESS_OFFSET),
                     mdioAddr);
    /* (Production: poll GB bit with timeout) */
    *RegDataPtr = (uint16)MCAL_REG32_READ(
                      IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_MDIO_DATA_OFFSET));
#endif
    return E_OK;
}

FUNC(Std_ReturnType, ETH_CODE)
Eth_17_GEthMac_WriteMii(
    VAR(uint8,  AUTOMATIC) CtrlIdx,
    VAR(uint8,  AUTOMATIC) PhyAddr,
    VAR(uint8,  AUTOMATIC) RegAddr,
    VAR(uint16, AUTOMATIC) RegData)
{
    (void)CtrlIdx;
#ifdef ETH_17_GETH_MAC_HOST_SIM
    (void)PhyAddr; (void)RegAddr; (void)RegData;
#else
    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_MDIO_DATA_OFFSET),
                     (uint32)RegData);

    uint32 mdioAddr = ((uint32)PhyAddr  << IFXETH_MDIO_PHYADDR_SHIFT) |
                      ((uint32)RegAddr  << IFXETH_MDIO_REGADDR_SHIFT)  |
                      ((uint32)Eth_17_GEthMac_Config.MdioCrValue << IFXETH_MDIO_CR_SHIFT) |
                      IFXETH_MDIO_WRITE | IFXETH_MDIO_GB;

    MCAL_REG32_WRITE(IFX_ETH_REG(MCAL_TC34XX_ETH0_BASE,
                                   IFXETH_MAC_MDIO_ADDRESS_OFFSET),
                     mdioAddr);
#endif
    return E_OK;
}
