/**
 * Det.c – Default Error Tracer stub
 * AUTOSAR Release 22-11
 *
 * In a full AUTOSAR stack the DET is generated by the tool-chain and may
 * forward errors to a logging back-end.  This stub records the last error
 * for test assertions and returns E_OK as required by the specification.
 */

#include "Det.h"

/* Last reported error – accessible from test code */
static uint16 Det_LastModuleId   = 0u;
static uint8  Det_LastInstanceId = 0u;
static uint8  Det_LastApiId      = 0u;
static uint8  Det_LastErrorId    = 0u;
static uint32 Det_ErrorCount     = 0u;

Std_ReturnType Det_ReportError(
    uint16 ModuleId,
    uint8  InstanceId,
    uint8  ApiId,
    uint8  ErrorId)
{
    Det_LastModuleId   = ModuleId;
    Det_LastInstanceId = InstanceId;
    Det_LastApiId      = ApiId;
    Det_LastErrorId    = ErrorId;
    Det_ErrorCount++;
    return E_OK;
}

Std_ReturnType Det_ReportRuntimeError(
    uint16 ModuleId,
    uint8  InstanceId,
    uint8  ApiId,
    uint8  ErrorId)
{
    return Det_ReportError(ModuleId, InstanceId, ApiId, ErrorId);
}

/* Test accessor functions */
uint8  Det_GetLastErrorId(void)    { return Det_LastErrorId; }
uint8  Det_GetLastApiId(void)      { return Det_LastApiId; }
uint16 Det_GetLastModuleId(void)   { return Det_LastModuleId; }
uint32 Det_GetErrorCount(void)     { return Det_ErrorCount; }
void   Det_Reset(void)             { Det_LastModuleId = 0u; Det_LastInstanceId = 0u;
                                     Det_LastApiId = 0u; Det_LastErrorId = 0u;
                                     Det_ErrorCount = 0u; }
