/**
 * Eth_17_GEthMac_Cfg.h – Pre-Compile Configuration
 * AUTOSAR Release R22-11 – Aurix TC34xx EQOS Ethernet Driver
 *
 * In production this file is generated by the AUTOSAR configuration tool
 * (EB Tresos / Vector DaVinci) from ARXML.  For the host-simulation demo
 * it is hand-crafted for a single 100BASE-T1 controller (ETH0).
 *
 * Hardware mapping:
 *   ETH0 (index 0) → RMII 50 MHz → TJA1100 PHY (addr 0x00)
 *                  → 100BASE-T1 cable
 *   MAC: 02:00:00:00:00:01 (locally administered)
 */

#ifndef ETH_17_GETH_MAC_CFG_H
#define ETH_17_GETH_MAC_CFG_H

#include "Compiler.h"    /* FUNC(), P2CONST(), P2VAR() macros */
#include "Std_Types.h"

/* =========================================================================
 * Module switches
 * ====================================================================== */

/** Number of Ethernet controllers managed by this driver instance */
#define ETH_17_GETH_MAC_CTRL_COUNT          (1u)

/** Controller index for ETH0 – passed to every MCAL API as CtrlIdx */
#define ETH_17_GETH_MAC_CTRL_IDX_0          (0u)

/** Enable Det_ReportError on invalid API parameters */
#define ETH_17_GETH_MAC_DEV_ERROR_DETECT    STD_ON

/** Enable Eth_17_GEthMac_GetVersionInfo() */
#define ETH_17_GETH_MAC_VERSION_INFO_API    STD_ON

/** Enable Eth_17_GEthMac_ReadMii() / Eth_17_GEthMac_WriteMii() */
#define ETH_17_GETH_MAC_MII_API             STD_ON

/* =========================================================================
 * Host-simulation switch
 * When defined, hardware register accesses are replaced by NodeTransport
 * UDP socket calls so the module runs on Linux/Windows without TC34xx HW.
 * Undefine to compile against real silicon (TriCore toolchain required).
 * ====================================================================== */
#ifndef ETH_17_GETH_MAC_HOST_SIM
#  define ETH_17_GETH_MAC_HOST_SIM
#endif

/* =========================================================================
 * DMA ring configuration (TX + RX)
 * Sizes must be power-of-2; hardware maximum per EQOS channel is 256.
 * ====================================================================== */

#define ETH_17_GETH_MAC_TX_DESC_COUNT       (8u)     /* TX ring depth */
#define ETH_17_GETH_MAC_RX_DESC_COUNT       (8u)     /* RX ring depth */

/** Maximum payload bytes per RX buffer (1518 = max standard Ethernet frame) */
#define ETH_17_GETH_MAC_RX_BUF_LEN         (1518u)

/* =========================================================================
 * PHY configuration – TJA1100 100BASE-T1 on RMII @ 50 MHz reference clock
 * ====================================================================== */

/** MDIO address (set by hardware strap on PHYAD[4:0] pins) */
#define ETH_17_GETH_MAC_PHY_ADDRESS         (0x00u)

/** MDC clock divider: CR=1 → MDC = HCLK/42 ≈ 2.38 MHz (HCLK = 100 MHz) */
#define ETH_17_GETH_MAC_MDIO_CR_VALUE       (1u)

/** Configure TJA1100 as PHY master (board-level topology decision) */
#define ETH_17_GETH_MAC_PHY_MASTER_MODE     STD_ON

/* =========================================================================
 * MAC address (locally administered; byte 0 bit 1 = 1 per IEEE 802)
 *   ETH_17_GETH_MAC_ADDR_HIGH = upper 2 bytes in big-endian
 *   ETH_17_GETH_MAC_ADDR_LOW  = lower 4 bytes in big-endian
 * ====================================================================== */

#define ETH_17_GETH_MAC_ADDR_HIGH           ((uint32)0x00000200u)  /* 02:00 */
#define ETH_17_GETH_MAC_ADDR_LOW            ((uint32)0x00000001u)  /* 00:00:00:01 */

/* =========================================================================
 * Static configuration object
 * Declared here; defined in Eth_17_GEthMac.c.
 * ====================================================================== */

/* Forward-declare the config type to avoid circular inclusion */
struct Eth_17_GEthMac_ConfigType_s;
typedef struct Eth_17_GEthMac_ConfigType_s Eth_17_GEthMac_ConfigType;

extern const Eth_17_GEthMac_ConfigType Eth_17_GEthMac_Config;

#endif  /* ETH_17_GETH_MAC_CFG_H */
